### ISSUE TITLE
Uncaught SyntaxError: expected expression, got '<'

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/instagram_feed#2]
I'm seeing this in the console on pages that do not contain the element selector:

`Uncaught SyntaxError: expected expression, got '<'`

**Comment by ghost** [comment]
@laryn I can't reproduce this. Can you please try the latest (git) version (I updated the jQuery.Instagram library version, maybe that fixes it?) and/or, failing that, provide steps so I can reproduce this issue myself?

**Comment by laryn** [comment]
If I can get STR I'll reopen. Perhaps it's unrelated to this module after all. 
*scratches head*
