### ISSUE TITLE
Update library

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/instagram_feed#3]
I had this on a site and happened to see it wasn't displaying anymore. Updating the library to the latest version seems to fix it.

**Comment by ghost** [comment]
Thanks @laryn! But why v3.0.2 and not [v3.0.4](https://github.com/jsanahuja/jquery.instagramFeed/releases/tag/3.0.4)?

**Comment by laryn** [comment]
Maybe I mistyped in the PR, I did grab the latest release.

**Comment by ghost** [comment]
PR code change also shows 3.0.2 though...

**Comment by laryn** [comment]
The new code didn't have that header at all and that must be where my typo began as I pasted the code under the header and then manually edited the version number. 😑

I can revise and resubmit when I'm by the computer again.

**Comment by ghost** [comment]
I see. The minified file doesn't have comments with the version number, etc., but the non-minified file does. So I updated the PR with the comments from the non-minified file.

**Comment by ghost** [comment]
Merged, thanks @laryn!
