### ISSUE TITLE
Provide an example of JQuery selector

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/instagram_feed#7]
It's always helpful for me to have an example in a case like this. I was just testing this module and it took me several tries and some research to figure out a workable JQuery selector.

How about adding something like: `Example = "div.insta-block".`

**Comment by ghost** [comment]
Thanks @stpaultim. Merged with a small change.

**Comment by stpaultim** [comment]
Thanks. Now seeing that the module might not work anyway.
